enum TokenKind {
    VARIABLE,
    NUMBER,
    BRACKET_SMALL_OPEN,
    BRACKET_SMALL_CLOSE,
    BRACKET_CURLY_OPEN,
    BRACKET_CURLY_CLOSE,
    SEMICOLON,
    EQUAL,
    DATATYPE_INT,
    DATATYPE_VOID,
    RETURN,
    MAIN,
    IF,
    COND,
    DOUBLE_EQUAL
};