#ifndef ENUMS_H
#define ENUMS_H

enum TokenKind {
    ERROR,
    NONE,
    VARIABLE,
    NUMBER,
    BRACKET_SMALL_OPEN,
    BRACKET_SMALL_CLOSE,
    BRACKET_CURLY_OPEN,
    BRACKET_CURLY_CLOSE,
    SEMICOLON,
    EQUAL,
    COMMA,
    EXCLAIMATION,
    AMPERSAND,
    IDENTIFIER_INT,
    IDENTIFIER_VOID,
    IDENTIFIER_CHAR,
    IDENTIFIER_STRING,
    VARIABLE_TYPE_CHAR,
    VARIABLE_TYPE_INT,
    VARIABLE_TYPE_INT_AMPERSAND,
    LITERAL_STRING,
    RETURN,
    MAIN,
    IF,
    WHILE,
    COND,
    DOUBLE_EQUAL,
    NOT_EQUAL,
    PLUS,
    MINUS,
    PRINTF,
    SCANF,
    // ADD,
    // SUBSTRACT
};

#endif